// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAunuow7GX949kfkREir8-dlIIVJyfIJr0',
    appId: '1:712333810476:web:f6b87241cbfa35ffd3aa89',
    messagingSenderId: '712333810476',
    projectId: 'nam-football',
    authDomain: 'nam-football.firebaseapp.com',
    storageBucket: 'nam-football.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7NY8RJtnqo-TkaFT-YNETKNTEjaw7LaI',
    appId: '1:712333810476:android:7363c8f9285c099cd3aa89',
    messagingSenderId: '712333810476',
    projectId: 'nam-football',
    storageBucket: 'nam-football.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1qM2Ai6QOFJzM8DHdkVipL_ftq-b0FHQ',
    appId: '1:712333810476:ios:f4378ba486a34a65d3aa89',
    messagingSenderId: '712333810476',
    projectId: 'nam-football',
    storageBucket: 'nam-football.appspot.com',
    iosBundleId: 'com.example.namFootball',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1qM2Ai6QOFJzM8DHdkVipL_ftq-b0FHQ',
    appId: '1:712333810476:ios:f4378ba486a34a65d3aa89',
    messagingSenderId: '712333810476',
    projectId: 'nam-football',
    storageBucket: 'nam-football.appspot.com',
    iosBundleId: 'com.example.namFootball',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAunuow7GX949kfkREir8-dlIIVJyfIJr0',
    appId: '1:712333810476:web:3ec4c7a0654eabe9d3aa89',
    messagingSenderId: '712333810476',
    projectId: 'nam-football',
    authDomain: 'nam-football.firebaseapp.com',
    storageBucket: 'nam-football.appspot.com',
  );
}
